apiVersion: v1
kind: Service
metadata:
  name: hello-nam
  labels:
    app: hello-nam
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-nam
    tier: hello-nam
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nam
  labels:
    app: hello-nam
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-nam
        tier: hello-nam
    spec:
      containers:
      - image: 192.168.19.5:5000/hello-nam:xxx
        name: hello-nam
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
          name: hello-nam


